### PR TITLE
FIX Forum statistics exclude spammers

### LINKED ISSUE #118: Ensure forum post and thread counts are excluding spam
Might be nice to get this fixed for 0.8.0

### PR DESCRIPTION
**Pull request by camfindlay**
Fixes #118 - @dhensby if you have a sec can you peer this?

### CODE REVIEW

**Comment by camfindlay** [comment]
@dhensby thinking maybe this could be a bug fix on 0.7 - I've added a method but not removed any api just refactored.

**Comment by camfindlay** [comment]
@tractorcow any change you could peer this? one of the last outstanding 0.8 fixes. I'll just backport to 0.7.

**Comment by dhensby** [comment]
This needs rebasing :(

File: code/model/ForumThread.php [hunk 1]
```diff
@@ -133,7 +133,7 @@ function getFirstPost() {
 	 * @return int
 	 */
 	function getNumPosts() {
-		return (int)DB::query("SELECT count(*) FROM \"Post\" WHERE \"ThreadID\" = $this->ID")->value();
+		return (int)DB::query(sprintf('SELECT COUNT(Post.ID) FROM Post LEFT JOIN Member ON Post.AuthorID = Member.ID WHERE ThreadID = %s AND Member.ForumStatus = \'Normal\'', $this->ID))->value();
```
Comment (dhensby) [inline code/model/ForumThread.php]: Please keep line length below 120 chars.

Can't we use the ORM to build this?

Something like:

```php
return Post::get()->filter(array(
    'Author.ForumStatus ' => 'Normal',
))->count();
```

File: code/pagetypes/ForumHolder.php [hunk 2]
```diff
@@ -208,26 +208,21 @@ public function Breadcrumbs($maxDepth = 20, $unlinked = false, $stopAtPageType =
...
+	 * @return int Returns the number of posts in this forum holder
 	 */
 	public function getNumPosts() {
-		return Post::get()
-			->innerJoin(ForumHolder::baseForumTable(),"\"Post\".\"ForumID\" = \"ForumPage\".\"ID\"" , "ForumPage")
-			->filter(array(
-				"ForumPage.ParentID" => $this->ID
-			))
-			->count();
+		return $this->getForumStatistics()['Posts'];
```
Comment (dhensby) [inline code/pagetypes/ForumHolder.php]: I'm 99% sure this syntax doesn't work in 5.3 (ie: you can't access the key of a returned array in this way)

You have to do:

```php
$stats = $this->getForumStatistics();

return isset($stats['Posts']) ? $stats['Posts'] : 0;
```

File: code/pagetypes/ForumHolder.php [hunk 3]
```diff
@@ -252,11 +242,24 @@ function getNumTopics() {
...
-			AND \"ForumPage\".\"ParentID\" = '" . $this->ID . "'")->value(); 		
+		return $this->getForumStatistics()['Authors'];
+	}
+
+	/**
+	 * Tally the number of posts, threads and authors from the Forum of this ForumHolder
+	 *
+	 * @return array Returns an key => value pair of the stats for the forum.
+	 */
+	public function getForumStatistics() {
```
Comment (dhensby) [inline code/pagetypes/ForumHolder.php]: This is going to be an expensive operation - there needs to be *some* level of caching somewhere in the system for this call

Comment (tractorcow) [inline code/pagetypes/ForumHolder.php]: I would recommend going back to a SQL only based approach. It can be awkward to have to re-implement business logic in sql, but you get the benefit of sql query caches, and not having to run tasks in o(n) for each request, (or is this o(n^2)? ). This is going to be a huge performance bottleneck.

Comment (camfindlay) [inline code/pagetypes/ForumHolder.php]: @tractorcow good point. Are you recommending reimplementing SQL approach for each of the getNumPost, getNumTopic, getNumAuthors method and removing this getForumStatistics method?

File: code/pagetypes/ForumHolder.php (hunk 2 above)
Comment (camfindlay) [inline code/pagetypes/ForumHolder.php]: Ha, yes my spidey-sense and a dirty feeling when I wrote this was probably a good indication that this was a non-5.3 feature. Will rework it to be 5.3 happy.

File: code/pagetypes/ForumHolder.php (hunk 3 above)
Comment (tractorcow) [inline code/pagetypes/ForumHolder.php]: If at all possible yes. :D

File: code/model/ForumThread.php (hunk 1 above)
Comment (camfindlay) [inline code/model/ForumThread.php]: 120 chars, fair call.

We used to have a lot of forum implemented in ORM however found we had performance issues. Subsequently a lot ended up getting reworked into SQL calls when we relaunched the ssilverstripe.org site last year. 

Any thoughts on ORM or SQL given speed concerns?

**Comment by camfindlay** [comment]
Will rebase and look to correct above issues.

**Comment by camfindlay** [comment]
@dhensby @tractorcow rebased and reworked.

File: code/model/ForumThread.php [hunk 4]
```diff
@@ -133,7 +133,15 @@ function getFirstPost() {
 	 * @return int
 	 */
 	function getNumPosts() {
-		return (int)DB::query("SELECT count(*) FROM \"Post\" WHERE \"ThreadID\" = $this->ID")->value();
+		return (int)DB::query(
```
Comment (tractorcow) [inline code/model/ForumThread.php]: We should double quote (ansi sql standard) all SQL identifiers. `Post.AuthorID` should be `"Post"."AuthorID"`. this helps cross-db connector compatibility. :D

File: code/model/ForumThread.php [hunk 5]
```diff
@@ -133,7 +133,15 @@ function getFirstPost() {
...
+			sprintf(
+				'SELECT COUNT(Post.ID)
+				FROM Post
+				INNER JOIN Member ON Post.AuthorID = Member.ID
+				WHERE ThreadID = %s AND Member.ForumStatus = \'Normal\'',
```
Comment (tractorcow) [inline code/model/ForumThread.php]: %d for numeric IDs is safer.

File: code/pagetypes/Forum.php [hunk 6]
```diff
@@ -357,25 +357,51 @@ function getLatestPost() {
 	 * @return int Returns the number of topics (threads)
 	 */
 	function getNumTopics() {
-		return DB::query(sprintf('SELECT COUNT("ID") FROM "ForumThread" WHERE "ForumID" = \'%s\'', $this->ID))->value();
+		return (int)DB::query(
+			sprintf(
+				'SELECT COUNT(Thread.ID)
+				FROM (SELECT Post.ID FROM Post
```
Comment (tractorcow) [inline code/pagetypes/Forum.php]: We can un-wrap this inner subquery for a slight mysql-side performance boost.

File: code/pagetypes/Forum.php [hunk 7]
```diff
@@ -357,25 +357,51 @@ function getLatestPost() {
...
 	 * @return int
 	 */
 	function getNumAuthors() {
-		return DB::query(sprintf('SELECT COUNT(DISTINCT "AuthorID") FROM "Post" WHERE "ForumID" = \'%s\'', $this->ID))->value();
+		return (int)DB::query(
+			sprintf(
+				'SELECT COUNT(DISTINCT AuthorID)
+				FROM Post
+				LEFT JOIN Member ON Post.AuthorID = Member.ID
+				WHERE Member.ForumStatus = \'Normal\' AND ForumID = \'%s\'',
```
Comment (tractorcow) [inline code/pagetypes/Forum.php]: As above, try to use `%d` for ID placeholders.

**Comment by camfindlay** [comment]
good feedback @tractorcow will continue to iterate when I get a moment. Can you expand on "unwrap" for the SQL statement above?

Unwrap the sql

**Comment by tractorcow** [comment]
It just means don't use a sub-query when you don't need to. Inner join is faster. I'm not even sure that the sql you wrote does what you think it does... have you tested the inner query in a sql editor against a datasource to make sure it worked?

**Comment by dhensby** [comment]
Raw SQL vs ORM:

```php
return Post::get()->filter(array(
    'Author.ForumStatus ' => 'Normal',
))->count();
```

Should produce the SQL you're hand-writing. I think the bottlekneck is the iterations over child posts and so on - and then the fact that the result isn't stored and is repeatedly requested. That's where the performance impact is coming from.

Implementing caching is better, eventual consistency for these numbers is ok.

File: code/model/ForumThread.php (hunk 4 above)
Comment (camfindlay) [inline code/model/ForumThread.php]: will do.

File: code/model/ForumThread.php (hunk 5 above)
Comment (camfindlay) [inline code/model/ForumThread.php]: thanks, yes sounds like a good thing.

File: code/pagetypes/Forum.php (hunk 6 above)
Comment (camfindlay) [inline code/pagetypes/Forum.php]: Sure, this was simply taken from the similar method in Forum class. Main issue is that Forum and ForumThread are only aware of each other by way of the Post class. I could INNER JOIN both Member and ForumThread on to Post though right @tractorcow ?

File: code/pagetypes/Forum.php (hunk 7 above)
Comment (camfindlay) [inline code/pagetypes/Forum.php]: agreed and on my todo.

**Comment by camfindlay** [comment]
Sounds like I need to benchmark SQL vs ORM and see ;)

**Comment by camfindlay** [comment]
Looks like SQL vs ORM is pretty close. Can someone enlighten me as to which would be easy to get some caching on?

# SQL

SELECT COUNT("Post"."ID") FROM "Post" INNER JOIN "Member" ON "Post"."AuthorID" = "Member"."ID" INNER JOIN "SiteTree" ON "Post"."ForumID" = "SiteTree"."ID" WHERE "SiteTree"."ParentID" = 30 AND "Member"."ForumStatus" = 'Normal' AND "Post"."Status" = 'Moderated' 1.0655s

SELECT COUNT("Post"."ID") FROM "Post" INNER JOIN "Member" ON "Post"."AuthorID" = "Member"."ID" INNER JOIN "SiteTree" ON "Post"."ForumID" = "SiteTree"."ID" WHERE "SiteTree"."ParentID" = 30 AND "Member"."ForumStatus" = 'Normal' AND "Post"."Status" = 'Moderated' 1.0654s

SELECT COUNT("Post"."ID") FROM "Post" INNER JOIN "Member" ON "Post"."AuthorID" = "Member"."ID" INNER JOIN "SiteTree" ON "Post"."ForumID" = "SiteTree"."ID" WHERE "SiteTree"."ParentID" = 30 AND "Member"."ForumStatus" = 'Normal' AND "Post"."Status" = 'Moderated' 1.0454s

SELECT COUNT("Post"."ID") FROM "Post" INNER JOIN "Member" ON "Post"."AuthorID" = "Member"."ID" INNER JOIN "SiteTree" ON "Post"."ForumID" = "SiteTree"."ID" WHERE "SiteTree"."ParentID" = 30 AND "Member"."ForumStatus" = 'Normal' AND "Post"."Status" = 'Moderated' 0.9652s

SELECT COUNT("Post"."ID") FROM "Post" INNER JOIN "Member" ON "Post"."AuthorID" = "Member"."ID" INNER JOIN "SiteTree" ON "Post"."ForumID" = "SiteTree"."ID" WHERE "SiteTree"."ParentID" = 30 AND "Member"."ForumStatus" = 'Normal' AND "Post"."Status" = 'Moderated' 1.0066s

SELECT COUNT("Post"."ID") FROM "Post" INNER JOIN "Member" ON "Post"."AuthorID" = "Member"."ID" INNER JOIN "SiteTree" ON "Post"."ForumID" = "SiteTree"."ID" WHERE "SiteTree"."ParentID" = 30 AND "Member"."ForumStatus" = 'Normal' AND "Post"."Status" = 'Moderated' 0.9941s



# ORM

SELECT count(DISTINCT "Post"."ID") AS "0" FROM "Post" INNER JOIN "SiteTree" ON "Post"."ForumID" = "SiteTree"."ID" INNER JOIN "Member" AS "AuthorStatusCheck" ON "AuthorStatusCheck"."ID" = "Post"."AuthorID" WHERE ("SiteTree"."ParentID" = '30') AND ("Post"."Status" = 'Moderated') AND ("AuthorStatusCheck"."ForumStatus" = 'Normal') 1.0405s

SELECT count(DISTINCT "Post"."ID") AS "0" FROM "Post" INNER JOIN "SiteTree" ON "Post"."ForumID" = "SiteTree"."ID" INNER JOIN "Member" AS "AuthorStatusCheck" ON "AuthorStatusCheck"."ID" = "Post"."AuthorID" WHERE ("SiteTree"."ParentID" = '30') AND ("Post"."Status" = 'Moderated') AND ("AuthorStatusCheck"."ForumStatus" = 'Normal') 1.0076s

SELECT count(DISTINCT "Post"."ID") AS "0" FROM "Post" INNER JOIN "SiteTree" ON "Post"."ForumID" = "SiteTree"."ID" INNER JOIN "Member" AS "AuthorStatusCheck" ON "AuthorStatusCheck"."ID" = "Post"."AuthorID" WHERE ("SiteTree"."ParentID" = '30') AND ("Post"."Status" = 'Moderated') AND ("AuthorStatusCheck"."ForumStatus" = 'Normal') 1.0179s

SELECT count(DISTINCT "Post"."ID") AS "0" FROM "Post" INNER JOIN "SiteTree" ON "Post"."ForumID" = "SiteTree"."ID" INNER JOIN "Member" AS "AuthorStatusCheck" ON "AuthorStatusCheck"."ID" = "Post"."AuthorID" WHERE ("SiteTree"."ParentID" = '30') AND ("Post"."Status" = 'Moderated') AND ("AuthorStatusCheck"."ForumStatus" = 'Normal') 1.0614s

SELECT count(DISTINCT "Post"."ID") AS "0" FROM "Post" INNER JOIN "SiteTree" ON "Post"."ForumID" = "SiteTree"."ID" INNER JOIN "Member" AS "AuthorStatusCheck" ON "AuthorStatusCheck"."ID" = "Post"."AuthorID" WHERE ("SiteTree"."ParentID" = '30') AND ("Post"."Status" = 'Moderated') AND ("AuthorStatusCheck"."ForumStatus" = 'Normal') 0.9988s

SELECT count(DISTINCT "Post"."ID") AS "0" FROM "Post" INNER JOIN "SiteTree" ON "Post"."ForumID" = "SiteTree"."ID" INNER JOIN "Member" AS "AuthorStatusCheck" ON "AuthorStatusCheck"."ID" = "Post"."AuthorID" WHERE ("SiteTree"."ParentID" = '30') AND ("Post"."Status" = 'Moderated') AND ("AuthorStatusCheck"."ForumStatus" = 'Normal') 1.0952s

**Comment by dhensby** [comment]
The query speeds there are close enough to call "identical" therefore (IMO) using the ORM is preferable as it reduced regression risks when/if core code changes.

Caching is pretty independent of the method of calling the SQL - we need the PHP function itself to cache the results and use the cache wherever possible.

**Comment by camfindlay** [comment]
Lots of nice Postgres errors :(

**Comment by camfindlay** [comment]
@dhensby right... finally sorted postgres fixes and have gone with a consistent SQLQuery approach due to some of the DISTINCT counts required. Think this is last items before a 0.8.0 release unless you want to try tackle that bug #124 that we reverted?

**Comment by dhensby** [comment]
Looks good.

The other issue requires such a big overhaul, I don't think it's safe to do in a minor release, I think it's a bug that will stay for a while.

**Comment by camfindlay** [comment]
Cheers, I'll gather a changelog and look at getting 0.8.0 release this week.

**Comment by tractorcow** [comment]
Nice job of tidying up this PR @camfindlay
